// eslint-disable-next-line filenames/match-exported
import "@material/react-button/dist/button.css";
import type { Metadata } from "next";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import "react-responsive-modal/styles.css";
import "react-toggle/style.css";
import "ress";
import Layout from "./_components/Layout";
import "./globals.css";

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "ポケター",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang="ja">
      <body>
        <NuqsAdapter>
          <Layout>{children}</Layout>
        </NuqsAdapter>
      </body>
    </html>
  );
}
