import type { Metadata } from "next";
import "./globals.css";
import "ress";
import "react-responsive-modal/styles.css";

export const metadata: Metadata = {
  title: "ポケター",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>{children}</body>
    </html>
  );
}
